- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:ThePrimeagen/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
